# Generated by Django 4.2.6 on 2024-08-05 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_team'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Item',
        ),
    ]
