# Generated by Django 4.2.6 on 2024-08-06 13:48

import autoslug.fields
from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('description', tinymce.models.HTMLField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('image', models.ImageField(upload_to='items')),
                ('period', models.CharField(choices=[('BREAK_FIST', 'BRAKE_FIST'), ('LUNCH', 'LUNCH'), ('DINNER', 'DINNER')], max_length=10)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='name')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
